language: 'english'
enabled: true
enabled-stats: true
update-notify-login: false
logging-settings:
  log-debug: false
  log-warning: true
  log-severe: true
world-settings:
  default-settings:
    min-night-speed: 1.0
    max-night-speed: 1.0
    speed-curve: 0.5
    instant-day:
      enabled: false
      ratio: 1.0
    tick-settings:
      weather: false
      random-tick: true
      random-tick-limit: 1000
    phantoms:
      reset-all-ratio: 0.5
      spawn-success-chance: 0.5
    morning-settings:
      clear-weather: true
      heal-sleeping-villagers: true
    sleep-rewards:
      potion-effects:
        heal:
          negative-effects:
            - BLINDNESS
            - CONFUSION
            - HARM
            - HUNGER
            - POISON
            - SLOW
            - SLOW_DIGGING
            - UNLUCK
            - WEAKNESS
            - WITHER
          positive-effects:
            - ABSORPTION
            - DAMAGE_RESISTANCE
            - FAST_DIGGING
            - FIRE_RESISTANCE
            - HEAL
            - HEALTH_BOOST
            - INCREASE_DAMAGE
            - JUMP
            - LUCK
            - NIGHT_VISION
            - REGENERATION
            - SATURATION
            - SPEED
            - WATER_BREATHING
          negative-require-hours: 3
          positive-require-hours: 3
        give:
          LUCK:
            duration-ticks: 3600
            amplifier: 1
            require-hours: 2
            ambient: true
            show-icon: true
          HASTE:
            duration-ticks: 3600
            amplifier: 1
            require-hours: 3
            ambient: true
            show-icon: true
  world:
    min-night-speed: 2.0
    max-night-speed: 30.0
